# Generated by Django 5.2.9 on 2026-01-08 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المؤلف")),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="السيرة الذاتية"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/avatars/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="التخصص"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="الموقع الإلكتروني"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مؤلف",
                "verbose_name_plural": "المؤلفون",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم التصنيف")),
                ("features", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=100, unique=True),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تصنيف",
                "verbose_name_plural": "التصنيفات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الكتاب"),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="books/pdfs/",
                        verbose_name="ملف PDF",
                    ),
                ),
                ("published_year", models.IntegerField(verbose_name="سنة النشر")),
                ("pages", models.IntegerField(verbose_name="عدد الصفحات")),
                (
                    "language",
                    models.CharField(
                        default="العربية", max_length=50, verbose_name="اللغة"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="PDF", max_length=50, verbose_name="صيغة الملف"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="السعر",
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="مجاني")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "downloads",
                    models.IntegerField(default=0, verbose_name="عدد التحميلات"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="عدد المشاهدات")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.category",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "كتاب",
                "verbose_name_plural": "الكتب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_read",
                    models.DateTimeField(auto_now=True, verbose_name="آخر قراءة"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="التقدم %")),
                (
                    "reading_duration_minutes",
                    models.IntegerField(default=0, verbose_name="مدة القراءة (دقيقة)"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="الكتاب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل القراءة",
                "verbose_name_plural": "سجلات القراءة",
                "ordering": ["-last_read"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="الكتاب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشارة مرجعية",
                "verbose_name_plural": "الإشارات المرجعية",
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                ("comment", models.TextField(verbose_name="التعليق")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.book",
                        verbose_name="الكتاب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة",
                "verbose_name_plural": "المراجعات",
                "ordering": ["-created_at"],
                "unique_together": {("book", "user")},
            },
        ),
    ]
