# Generated by Django 5.2.9 on 2026-01-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.author",
                verbose_name="المؤلف",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="اسم المؤلف (إذا لم يكن مسجلاً)",
            ),
        ),
    ]
