# Generated by Django 5.2.9 on 2026-01-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_author_book_author_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "تسجيل دخول"),
                            ("view_book", "عرض كتاب"),
                            ("read_book", "قراءة كتاب"),
                            ("review", "إضافة تقييم"),
                            ("bookmark", "إضافة إشارة مرجعية"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط المستخدم",
                "verbose_name_plural": "أنشطة المستخدمين",
                "ordering": ["-visited_at"],
            },
        ),
    ]
