# Generated by Django 5.2.9 on 2026-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_readinghistory_reading_duration_minutes_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="downloads",
            field=models.IntegerField(default=0, verbose_name="عدد التحميلات"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="books/pdfs/", verbose_name="ملف PDF"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="views",
            field=models.IntegerField(default=0, verbose_name="عدد المشاهدات"),
        ),
    ]
