# Generated by Django 5.2.9 on 2026-10-08 09:02

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_import_legacy_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='search_document',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='work',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
