# Generated by Django 5.2.9 on 2026-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_weight', models.FloatField(default=3.0, verbose_name='وزن تطابق العنوان')),
                ('text_weight', models.FloatField(default=2.0, verbose_name='وزن تطابق النص الكامل')),
                ('free_access_bonus', models.FloatField(default=0.4, verbose_name='مكافأة الوصول المجاني الموثّق')),
                ('verified_bonus', models.FloatField(default=0.2, verbose_name='مكافأة البيانات المُتحقق منها')),
                ('arabic_bonus', models.FloatField(default=0.5, verbose_name='مكافأة المحتوى العربي')),
                ('recency_weight', models.FloatField(default=0.1, verbose_name='وزن الحداثة')),
                ('typo_threshold', models.FloatField(default=0.45, help_text='0-1. الأقل = تساهل أكبر مع الأخطاء الإملائية.', verbose_name='حد التشابه لتحمّل الأخطاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات ترتيب البحث',
                'verbose_name_plural': 'إعدادات ترتيب البحث',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(help_text='مصطلح في كل سطر، مثل: الذكاء الاصطناعي / artificial intelligence / AI', verbose_name='المصطلحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'مرادفات',
                'verbose_name_plural': 'المرادفات',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='نص البحث')),
                ('normalized_query', models.CharField(db_index=True, max_length=200, verbose_name='النص المطبّع')),
                ('results', models.PositiveIntegerField(verbose_name='عدد النتائج')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='التصفية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'عملية بحث',
                'verbose_name_plural': 'سجل البحث',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['results', 'created_at'], name='search_sear_results_6d2f12_idx')],
            },
        ),
    ]
