# Generated by Django 5.2.9 on 2026-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('provider_key', models.CharField(blank=True, help_text='يربط المصدر بتنفيذ SourceProvider في الكود (فارغ للإدخال اليدوي).', max_length=50, verbose_name='مفتاح المزوّد')),
                ('source_type', models.CharField(choices=[('LIBRARY', 'مكتبة'), ('REPOSITORY', 'مستودع'), ('AGGREGATOR', 'مُجمِّع بيانات'), ('PUBLISHER', 'ناشر'), ('UNIVERSITY', 'جامعة'), ('GOVERNMENT', 'جهة حكومية'), ('AUTHOR', 'المؤلف'), ('MANUAL', 'إدخال يدوي'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='النوع')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='الجهة المالكة')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='النطاق')),
                ('homepage_url', models.URLField(blank=True, verbose_name='الموقع')),
                ('has_api', models.BooleanField(default=False, verbose_name='يوفر API')),
                ('supports_search', models.BooleanField(default=False, verbose_name='يدعم البحث')),
                ('supports_metadata', models.BooleanField(default=False, verbose_name='يوفر بيانات وصفية')),
                ('legal_access_policy', models.TextField(blank=True, help_text='ما المسموح: فهرسة البيانات؟ الربط؟ إعادة الاستضافة؟ مع رابط الشروط.', verbose_name='سياسة الوصول القانونية')),
                ('allows_rehosting', models.BooleanField(default=False, help_text='لا تفعّله إلا بوجود نص صريح في شروط المصدر أو رخصة المحتوى.', verbose_name='يسمح بإعادة الاستضافة')),
                ('terms_url', models.URLField(blank=True, verbose_name='رابط الشروط')),
                ('metadata_license', models.CharField(blank=True, max_length=100, verbose_name='رخصة البيانات الوصفية')),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الطلبات/دقيقة')),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='الأعلى أولًا عند التعارض.', verbose_name='الأولوية')),
                ('reliability', models.PositiveSmallIntegerField(default=50, help_text='تدخل في ترتيب نتائج البحث وجودة البيانات.', verbose_name='الموثوقية (0-100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('health_status', models.CharField(choices=[('UNKNOWN', 'غير معروف'), ('OK', 'يعمل'), ('DEGRADED', 'متقطع'), ('DOWN', 'متوقف')], default='UNKNOWN', max_length=10, verbose_name='الحالة')),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فحص')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مصدر',
                'verbose_name_plural': 'المصادر',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
