# Generated by Django 5.2.9 on 2026-10-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_seed_manual_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'قيد التشغيل'), ('DONE', 'اكتمل'), ('FAILED', 'فشل')], default='RUNNING', max_length=10, verbose_name='الحالة')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='المعاملات')),
                ('seen', models.PositiveIntegerField(default=0, verbose_name='سجلات مقروءة')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='أُنشئ')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='حُدّث')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='تُخطّي')),
                ('duplicates', models.PositiveIntegerField(default=0, verbose_name='مكرر')),
                ('files_downloaded', models.PositiveIntegerField(default=0, verbose_name='ملفات نُزّلت')),
                ('bytes_downloaded', models.BigIntegerField(default=0, verbose_name='حجم التنزيل (بايت)')),
                ('errors', models.PositiveIntegerField(default=0, verbose_name='أخطاء')),
                ('log', models.TextField(blank=True, verbose_name='السجل')),
                ('cursor', models.TextField(blank=True, help_text='resumption token أو موضع للاستكمال لاحقًا.', verbose_name='نقطة الاستكمال')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='sources.source', verbose_name='المصدر')),
            ],
            options={
                'verbose_name': 'عملية استيراد',
                'verbose_name_plural': 'عمليات الاستيراد',
                'ordering': ['-started_at'],
            },
        ),
    ]
